[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#FF6B6B"          # Coral red for highlights
backgroundColor="#FFFDF9"       # Warm off-white
secondaryBackgroundColor="#FFEEDA"   # Soft pastel peach panels
textColor="#2E2E2E"             # Almost-black elegant text
font="serif"
