[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#1B86EC"         # Modern blue for highlights
backgroundColor="#FFFFFF"      # White clean background
secondaryBackgroundColor="#F0F2F6"   # Soft grey for cards
textColor="#31333F"            # Dark grey text for readability
font="sans serif"
