# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="light"
# primaryColor="#FF6B6B"          # Coral red for highlights
# backgroundColor="#FFFDF9"       # Warm off-white
# secondaryBackgroundColor="#FFEEDA"   # Soft pastel peach panels
# textColor="#2E2E2E"             # Almost-black elegant text
# font="serif"

# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="light"
# primaryColor="#0077B6"          # Deep ocean blue
# backgroundColor="#E0F7FA"       # Aqua mist
# secondaryBackgroundColor="#CAF0F8"   # Soft sky cyan
# textColor="#023E8A"             # Navy blue text
# font="sans serif"

# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="light"
# primaryColor="#2ECC71"          # Emerald green
# backgroundColor="#FAFFFB"       # Pure fresh white
# secondaryBackgroundColor="#E8F8F5"   # Mint shade
# textColor="#145A32"             # Dark forest green text
# font="serif"


# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="dark"
# primaryColor="#FFD700"          # Royal gold
# backgroundColor="#0A0A0A"       # Pure matte black
# secondaryBackgroundColor="#1C1C1C"   # Charcoal panels
# textColor="#EAEAEA"             # Soft silver-white text
# font="sans serif"


import streamlit as st

# Choose your vibe 🌟
THEME = "Ocean"   # 🔄 Change: "Ocean" | "Sunset" | "Neon" | "Emerald"

gradients = {
    "Ocean": {
        "bg": "linear-gradient(135deg, #2E3192, #1BFFFF)",
        "sidebar": "linear-gradient(180deg, #0F2027, #203A43, #2C5364)",
        "button": "linear-gradient(90deg, #00C9FF, #92FE9D)",
        "shadow": "#00C9FF"
    },
    "Sunset": {
        "bg": "linear-gradient(135deg, #FF512F, #DD2476)",
        "sidebar": "linear-gradient(180deg, #200122, #6f0000)",
        "button": "linear-gradient(90deg, #F7971E, #FFD200)",
        "shadow": "#FFD200"
    },
    "Neon": {
        "bg": "linear-gradient(135deg, #8E2DE2, #4A00E0)",
        "sidebar": "linear-gradient(180deg, #0F0C29, #302B63, #24243E)",
        "button": "linear-gradient(90deg, #FF00CC, #333399)",
        "shadow": "#FF00CC"
    },
    "Emerald": {
        "bg": "linear-gradient(135deg, #11998E, #38EF7D)",
        "sidebar": "linear-gradient(180deg, #00416A, #E4E5E6)",
        "button": "linear-gradient(90deg, #56ab2f, #a8e063)",
        "shadow": "#56ab2f"
    }
}

css = f"""
<style>
.stApp {{
    background: {gradients[THEME]['bg']};
    color: white;
}}

section[data-testid="stSidebar"] {{
    background: {gradients[THEME]['sidebar']};
}}

.stButton > button {{
    background: {gradients[THEME]['button']};
    color: white;
    border: none;
    border-radius: 10px;
    padding: 0.6em 1.2em;
    font-weight: 600;
    transition: 0.3s;
}}
.stButton > button:hover {{
    transform: scale(1.05);
    box-shadow: 0px 0px 12px {gradients[THEME]['shadow']};
}}
</style>
"""

st.markdown(css, unsafe_allow_html=True)
