[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"
primaryColor="#00E5FF"         # Neon cyan for highlights
backgroundColor="#0E1117"      # Deep charcoal background
secondaryBackgroundColor="#262730"   # Slightly lighter panels
textColor="#FAFAFA"            # Bright white text
font="sans serif"
