# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="light"
# primaryColor="#FF6B6B"          # Coral red for highlights
# backgroundColor="#FFFDF9"       # Warm off-white
# secondaryBackgroundColor="#FFEEDA"   # Soft pastel peach panels
# textColor="#2E2E2E"             # Almost-black elegant text
# font="serif"

# [server]
# headless = true
# enableCORS = false
# enableXsrfProtection = false

# [theme]
# base="light"
# primaryColor="#0077B6"          # Deep ocean blue
# backgroundColor="#E0F7FA"       # Aqua mist
# secondaryBackgroundColor="#CAF0F8"   # Soft sky cyan
# textColor="#023E8A"             # Navy blue text
# font="sans serif"


[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"
primaryColor="#FF00FF"          # Neon magenta
backgroundColor="#0D0D0D"       # True black
secondaryBackgroundColor="#1A1A1A"   # Dark grey panels
textColor="#00FFFF"             # Neon cyan text
font="monospace"

